### ISSUE TITLE
Calendar / Access

### ISSUE THREAD

**Issue by melonasnm** [PassageTech/Milestones-PM-Plus#10]
Hello,

Unfortunately my calendar isn't working for Milestones PM+ for Salesforce. If I create dates for Projects, Milestones, or Tasks, they don't show up on the calendar. Below is a link to the screen shot. Also when I tried to grant access, Passage Tech was not listed to grant access into our org. Please let me know how this can be fixed. Thank you!
https://www.dropbox.com/s/7xj9bpd6ti7flo2/Screenshot%202014-11-17%2014.41.47.png?dl=0

**Comment by jerryreid** [comment]
@melonasnm This has been fixed in the latest release.
