### ISSUE TITLE
Font size on Summary Tab

### ISSUE THREAD

**Issue by eric19h** [PassageTech/Milestones-PM-Plus#18]
After installing PM+ I noticed that the font size is larger only when I'm looking at the Summary Tab in the Project Management App.  When I click any other tab in the app, or any other tab in any other app, the font size is normal.  I can't find anywhere that would have such a localized font change.  I check my browser and it remains at 100% on every tab.

**Comment by jerryreid** [comment]
@eric19h This has been fixed in the latest release.
