### ISSUE TITLE
Open tasks scheduled for the same day not appearing in sequence

### ISSUE THREAD

**Issue by aplssf** [PassageTech/Milestones-PM-Plus#23]
When I create an open task and link it to a predecessor task, that predecessor task still sometimes appears after the successor task in the Gantt chart (which appears to be ordered by due date, then in alphabetical order for task name, without taking into account any link to predecessor tasks).

This makes the sequence harder to follow, with the Gantt chart appearing to show the sequence of tasks backtracking on themselves.

Could the Passage Technology team please consider this for an enhancement?

**Comment by aplssf** [comment]
If no one can reconfigure the Gantt chart to show tasks (and milestones) in sequence, can anyone explain how the apex determines which milestones should appear first?

Tasks are displayed in alphabetical order but I can't figure out the logic for milestones - see below.

![image](https://cloud.githubusercontent.com/assets/10284831/5783058/d4b99514-9db7-11e4-8227-f524e720208d.png)

**Comment by jerryreid** [comment]
The sorting logic on the gantt chart is to order in an ascending fashion,
first on the start date, then the end date, and then finally on the name of
the item. How would you like them to be sequenced?

**Comment by aplssf** [comment]
Thanks for the reply Jerry, I deleted my comment immediately after I posted it because I realised that my gantt chart only appeared out of sequence because I had got a start date wrong. The logic you've described makes perfect sense.

**Comment by aplssf** [comment]
To clarify, the Gantt chart works perfectly for Milestones but still does't for tasks - again, it needs to take into account the sequence of predecessor and successor tasks.

**Comment by jerryreid** [comment]
@aplssf  As long as the predecessor task has an earlier start date, it will appear in the correct order. Can you share with me an export of your project for testing and an example of two tasks connected via a relationship that is wrong?

**Comment by aplssf** [comment]
@jerryreid that's the problem, if the start date for two tasks is the same day then they're sorted in alphabetical order. Which means that the successor task often appears first with an arrow that goes backwards, to connect it to the predecessor.

Obviously this is a much more common issue for tasks than milestones.

![image](https://cloud.githubusercontent.com/assets/10284831/5814495/f43b148e-a083-11e4-8cf2-6ab97af977cc.png)

It makes a chart particularly difficult to read when 2+ predecessor tasks are linked to a successor (see the area inside the red box).

**Comment by aplssf** [comment]
Hi Jerry, was that attachment what you needed or did you need some sort of
XML download?

**Comment by jerryreid** [comment]
The XML export would be helpful when we get to testing.

**Comment by jerryreid** [comment]
This has been fixed in version 3.3.

**Comment by aplssf** [comment]
Thank you Jerry.

**Comment by aplssf** [comment]
@jerryreid I must be missing something here - the tasks still aren't appearing in a sequence that's based on their predecessor. Do I need to deploy a component that won't have been activated immediately when I installed v 3.3 or change the custom task order? If it's the latter, could you please post the format for formula?

**Comment by aplssf** [comment]
![deletion error](https://cloud.githubusercontent.com/assets/10284831/6085413/585181a0-ae31-11e4-91d5-47e91c37df7a.jpg)

**Comment by aplssf** [comment]
![task order](https://cloud.githubusercontent.com/assets/10284831/6085417/650f7bc2-ae31-11e4-90b1-f96dd2dc590e.jpg)

**Comment by aplssf** [comment]
Apologies, please ignore this post for now, the issue may just be my own sequencing!

**Comment by aplssf** [comment]
I've checked and it's definitely not getting the order right.

**Comment by aplssf** [comment]
![task order 2](https://cloud.githubusercontent.com/assets/10284831/6086186/b34aeeec-ae37-11e4-8a2f-6d95a07765b9.jpg)

**Comment by jerryreid** [comment]
Please confirm if this is still an issue.


--
Best Regards,

Jerry Reid
Passage Technology
www.passagetech.com
jerry.reid@passagetech.com
Direct: 1-224-552-0080
Twitter:  @passagetech

**Comment by aplssf** [comment]
It is still an issue.

**Comment by shawn905** [comment]
This issue can be resolved by adjusting the 'Custom Task Sort Order' value in the custom settings. I believe for this specific example given above the following value in the custom setting should work. 

Predecessor_Task__r.Predecessor_Task__r.Due_Date__c asc, Predecessor_Task__r.Due_Date__c asc, Start_Date__c asc, Due_Date__c asc, Name asc

**Comment by aplssf** [comment]
Hi Shawn, thanks for getting back to me so soon with your suggestion.

I hate to be critical when I've received such fantastic support from you and your team but this solution is slightly missing the point. If a task has a predecessor task then the start date / due date / name of that task is should not be referenced, the predecessor needs to appear before it's successor regardless.

If there's two predecessor tasks or a task has no predecessor, then the logic that you've provided is spot on. But otherwise the order needs to be solely based on the sequence of predecessors and successors.

For my particular example the sort logic hasn't quite worked.

![task order gantt chart](https://cloud.githubusercontent.com/assets/10284831/6110679/39948e3c-b07b-11e4-94c9-8e2c6b091485.png)

**Comment by shawn905** [comment]
@aplssf We plan on making future enhancements to improve this area of the application. One way to improve this area is by adding WBS element numbering.

When I wrote the sort order logic above I was looking at the wrong picture. I have adjusted the sort order logic a little bit. After my adjustments it appears to be sorting properly. Please try the following sort order logic in the custom setting.

Predecessor_Task__r.Predecessor_Task__r.Due_Date__c asc, Predecessor_Task__r.Due_Date__c asc, Predecessor_Task__r.name desc, Start_Date__c asc, Due_Date__c asc, Name asc

**Comment by shawn905** [comment]
@aplssf For the time being you may also try numbering the task names. (ex: 1. call to discuss templates, 2. Prepare proposal template, 3. Create rebate fields, etc..)

**Comment by aplssf** [comment]
@shawn905 I really appreciate you taking the time to come up with the new sort order, without some sort of guide I wouldn't have known that was possible, that's now working perfectly for this set of tasks.

![image](https://cloud.githubusercontent.com/assets/10284831/6124686/6bbd7b12-b107-11e4-8137-736557edcde1.png)

The WBS element number would certainly be useful to me and our other users.

Thanks for the suggestion about numbering tasks, obviously it would work but I'm trying to stay away from that solution because it make reordering tasks more time consuming.

This is as near to a complete solution as I'd hope to get to, in such a short space of time and I'll be looking forward to the enhancements in the future.
