### ISSUE TITLE
Changing Date Format In Gantt Chart

### ISSUE THREAD

**Issue by aplssf** [PassageTech/Milestones-PM-Plus#24]
This may already be possible - can the date format in the Gantt charts be changed to the standard UK format (dd/mm/yyyy)?

Because we've set our locale, all of our other dates in Salesforce are already in this format and it confuses users.

**Comment by jerryreid** [comment]
@aplssf This has been fixed in our latest release. Just upgrade to get the latest. It may take a while for the links to update and point to the latest release.

**Comment by aplssf** [comment]
Great, thanks for letting me know Jerry and for making the fix so soon. The link is updated now.
