### ISSUE TITLE
App Update Notifications

### ISSUE THREAD

**Issue by aplssf** [PassageTech/Milestones-PM-Plus#28]
Could a thread be started or an alternative tool set up which users can subscribe to, to receive notifications when the app is updated?

Someone from the Passage Technologies support team has suggested that I subscribe to all GitHub notifications for this repository but that means I end up receiving a lot of irrelevant notifications.

I've had a look at the various GitHub features and can't see an obvious tool that could be used so I'm afraid I can't suggest any possible solutions.

**Comment by jerryreid** [comment]
Hi there, we appreciate your feedback.

At this time there isn't a plan to build in any notification process or solution, but that could change in the future if the need becomes stronger.

At present, you can periodically inspect this repository to learn of new functionality.
