### ISSUE TITLE
Project name error on chart groupings

### ISSUE THREAD

**Issue by aplssf** [PassageTech/Milestones-PM-Plus#35]
I've experienced this issue on several graphs now - when I group by project name in a report and then display that grouping on a chart, what looks like the API name? is displayed, instead of the value showing in the report.

![chart error 1](https://cloud.githubusercontent.com/assets/10284831/5793269/bb9e1fc6-9f35-11e4-9ac5-040765323c54.jpg)

![chart error 2](https://cloud.githubusercontent.com/assets/10284831/5793253/3121edfa-9f35-11e4-9492-1b8e147b8df4.jpg)

The project names should be W/C 5th Jan, Sales KPI Report Setup, W/C 12th Jan and Echosign Contracts Setup.

This is a matrix report and custom report type, showing tasks with or without times.

**Comment by aplssf** [comment]
Hi Jerry, did you see this issue?

**Comment by jerryreid** [comment]
This is not a project lookup field, but rather a hyperlink to get to the project field. If there is not a project name / project lookup field on the task object, we will have to add one in the future release or you can add one in your implementation.

**Comment by aplssf** [comment]
Thanks for the reply.

I see what you're saying, I hadn't come across something like this before.

If I can filter the lookup so that it picks up the project name without me having to search for it then I'm happy to add it myself but I'm not sure what criteria to use for the filter, is it possible?

I'm sure I'm not the only user who would benefit from this and in the longer term, I'd like to avoid having two of the same field which are basically showing the same value. So it may be worth considering for a future release.

**Comment by jerryreid** [comment]
Alex, I agree this would be a good change to make. I believe we already have this as an accelerator, but I have to check. It should be part of the free package because some people want to see tasks on the project page.

**Comment by aplssf** [comment]
Thanks for the update, that's good to hear.

**Comment by jerryreid** [comment]
The project lookup from tasks is now available in version 3.5.

**Comment by aplssf** [comment]
Great, thank you Jerry.
