### ISSUE TITLE
Errors Deploying 

### ISSUE THREAD

**Issue by ckeithsmith** [PassageTech/Milestones-PM-Plus#59]
Receiving errors when when attempting to deploy into a clean, new DE: 

Failures:
objects/Milestone1_Task__c.object(159,26):In field: LastReferencedDate - no CustomField named Milestone1_Task__c.LastReferencedDate found
settings/Address.settings(Address):Cannot modify label for state Taiwan with iso code 71 to Chinese Taipei in country China
settings/Case.settings(Case):In field: defaultCaseOwner - no User named jerry@22demo.com found

Workable one available?

**Comment by shawn905** [comment]
@ckeithsmith Try deploying without the settings folder.

**Comment by ckeithsmith** [comment]
Thanks...any idea on the missing LastReferencedDate field error?

**Comment by shawn905** [comment]
@ckeithsmith I have just updated the task object in the repository. You should be able to deploy now.

**Comment by ckeithsmith** [comment]
@shawn905 Thanks for the update on task object but it looks like there is the same issue with another date field..this time LastViewedDate: 

objects/Milestone1_Task__c.object(159,26):In field: LastViewedDate - no CustomField named Milestone1_Task__c.LastViewedDate found

settings/Address.settings(Address):Cannot modify label for state Taiwan with iso code 71 to Chinese Taipei in country China

**Comment by shawn905** [comment]
@ckeithsmith to resolve this issue you may need to remove all of the standard fields in field set created for the milestone task object. This is because these fields are not defined in the milestone task objects meta data (in the repository). Another option would be to create the Milestone1_Task__c object in your DE and try to deploy again.

**Comment by ckeithsmith** [comment]
@shawn905 Shawn, thanks for the help.  I did try creating the object in the DE then redeploying but still failed.   What do you think is the best way to remove the standard fields in the field set?  When I try to deploy from the IDE, I get errors and it fails.   I have tried with Workbench and using Andy Fawcett tool> https://githubsfdeploy.herokuapp.com/ .  I can't get a successful install from any approach.  

Any advice is welcomed and appreciated...

**Comment by shawn905** [comment]
You may open the Milestone1_Task__c object in your IDE and COPY everything between the <fieldset> tags. You may then delete the contents, deploy the object, then after deployment you may paste back in the field set. 

Unfortunately, we will not be able to provide any additional support as this appears to be a local deployment issue unrelated to our package and not a product defect. If you require additional assistance implementing Milestones PM+ for you client please consider ordering a support plan with Passage Technology, http://www.passagetechnology.com/salesforce1-helper-order/

Another option to avoid deployment issues would be to install the managed package from the AppExchange, https://appexchange.salesforce.com/listingDetail?listingId=a0N30000009uYYMEA2
