### ISSUE TITLE
Insufficient privileges error

### ISSUE THREAD

**Issue by aduperault** [PassageTech/Milestones-PM-Plus#61]
Hi, when creating a milestone for a related project one of my users is receiving an insufficient privileges to access error, despite having shared read/write access to both the project and milestones objects. The user profile can read/edit on Projects and create/read/edit on Milestones. The user is the same level as the record owner in the role hiearchy. If I grant manual sharing to the user, he can create the milestone. If I grant manual sharing to the group the user is in, he cannot create the milestone.

Projects and Milestones set to private with sharing rules to the group.
The user is part of this group. 
The user is the same level as the record owner.
The user has the read and edit permission on Project.
The user has the read, create, edit permission Milestone.
The user can edit the project record through the sharing rules. 
From the project record, the user cannot create a new milestone due to "insufficient privileges to access project."

Any ideas on how to fix this? thanks so much.

**Comment by jerryreid** [comment]
@aduperault Would you be able to grant login access to your org to Passage Technology? I think in order to see if this is a bug or security configuration error, we will need to get access to the environment to run debug logs or even to temporarily change security changes (e.g. change organization wide sharing to public readonly vs public read -write).

**Comment by aduperault** [comment]
Hi @jerryreid, for our production org, we can do a WebEx session where we grant sysadmin controls but would have to monitor the actions or we can grant login access to our sandbox environment. 
Right now the security is set to private and we control access through sharing rules to a group by project and milestone record type and would prefer to keep it that way (in other words, we don't want certain users having view-access to certain projects).

**Comment by jerryreid** [comment]
@aduperault Do you have queues enabled for any Milestones PM+ objects?

**Comment by aduperault** [comment]
@jerryreid No, we don't have any queues right now - I can try that to see if that fixes it. Right now, it's just record types, groups and OWD private w/sharing rules. We have two project teams that work on different very projects. Project team members that are working on the same project type should be able to see/edit the record and create/edit related milestones. They shouldn't see the other team's projects. I'll try queues...and will let you know. Thank you for your help!

**Comment by aduperault** [comment]
@jerryreid tried the queues but it's triggering an apex error (see below) when I try to change ownership. I can't create a sharing rule based on queue ownership.

Error: Apex trigger MPM4_BASE.Milestone1_Project_Trigger caused an unexpected exception, contact your administrator: MPM4_BASE.Milestone1_Project_Trigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id a1Nd0000004Ql9uEAC; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, MPM4_BASE.Milestone1_Milestone_Trigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id a1Rd0000001fiySEAQ; first error: FIELD_INTEGRITY_EXCEPTION, Assigned To: id value of incorrect type: 00Gd00000021vqDEAQ: [MPM4_BASE__Assigned_To__c] (MPM4_BASE) : []: (MPM4_BASE)

**Comment by jerryreid** [comment]
@aduperault Please upgrade to the latest version of Milestones PM+ to avoid this bug. This issue is independent from the issue you reported and at this stage there is no fix for the insufficient privs error, but I have reported it as a bug internally for now.

production: pm.passagetech.com
sandbox: pm-test.passagetech.com

**Comment by aduperault** [comment]
@jerryreid The upgrade removed the apex error regarding changing ownership to queues. The insufficient privileges error still occurs when a project group member tries to create a new milestone for an existing project (even if s/he has read/write access because through sharing rules).

![image](https://cloud.githubusercontent.com/assets/9436450/7403714/77d5d660-ee8d-11e4-95c4-df9fd6d92bdb.png)

**Comment by aduperault** [comment]
@jerryreid Hi, I'm not sure if anything changed, but I do not receive the error message above. If there is way we can remove the bug label and marked it resolved that  would be great. Thank you! Our staff loves this app.

**Comment by jerryreid** [comment]
This is fixed in the latest release available via the AppExchange, via this GitHub repository, or via the upgrade links:

production: pm.passagetech.com
sandbox: pm-test.passagetech.com
