### ISSUE TITLE
gant chart view

### ISSUE THREAD

**Issue by CGCGadmin** [PassageTech/Milestones-PM-Plus#9]
I'm experimenting with milestone PM+ from Milestone PM and I notice 1 main issue:
I can't click and drag the milestones in the gantt chart to adjust the dates.  

Also, when I set a predecessor milestone, it does not give the visual connection (aarow) to show the relationship between 2 milestones.  

Please advise on where I am going wrong with this.

**Comment by jerryreid** [comment]
Our gantt chart now shows milestones icons for items that start and end on the same day. When predecessor relationships exist, they are denoted by an arrow on the gantt chart.

At the moment, we are not planning to make the gantt chart click-and-drag-able as most schedule changes can be administered easily on the appropriate page, but if more people express interest for why this should be done at the gantt chart level, we may bring this up for consideration at a later date.
